.vscode/settings.json, dg/utils/openshift.py, setup.py
- Remove [OpenShift Python client](https://github.com/openshift/openshift-restclient-python) until new version using [Kubernetes Python client](https://github.com/kubernetes-client/python) >= 12.0.0 is released.
=> Remove OpenShift Python client

dg/lib/cloud_pak_for_data/cpd_3_0_1/cpd_manager.py, dg/lib/cloud_pak_for_data/cpd_3_5_0/cpd_manager.py, dg/lib/cloud_pak_for_data/cpd_manager.py
- Remove superfluous `--version` option when installing an assembly. This option also prevented the installation of certain assemblies with versions being different from the corresponding IBM Cloud Pak for Data version.
=> Remove --version option when installing an assembly

dg/commands/cluster/install_assembly.py, dg/commands/cluster/install_cloud_pak_for_data.py, dg/commands/cluster/install_data_gate.py, dg/commands/cluster/install_db2.py, dg/commands/cluster/login.py, dg/commands/fyre/cluster/copy_ssh_key.py, dg/commands/fyre/cluster/get_cluster_access_token.py, dg/commands/fyre/cluster/init_node_for_data_gate.py, dg/commands/fyre/cluster/init_node_for_db2.py, dg/commands/fyre/cluster/install_nfs_storage_class.py, dg/commands/fyre/cluster/login.py, dg/config/__init__.py, dg/config/binaries_manager.py, dg/config/cluster_credentials_manager.py
- Improve import dependencies between `dg.config` and `dg.config.cluster_credentials_manager` packages to avoid circular dependencies.
- Use `dg.config.data_gate_configuration_manager` to obtain configuration directories.
- Lazily load `~/.dg/binaries.json` to support mocking.
=> Improve import dependencies

README.md, dg/commands/cluster/install_assembly.py, dg/commands/cluster/install_cloud_pak_for_data.py, dg/commands/cluster/install_data_gate.py, dg/commands/cluster/install_db2.py, dg/config/__init__.py, dg/lib/click.py, dg/lib/cloud_pak_for_data/cpd_3_0_1/cpd_manager.py, dg/lib/cloud_pak_for_data/cpd_3_5_0/cpd_manager.py, dg/lib/cloud_pak_for_data/cpd_manager.py, dg/lib/download_manager/__init__.py, setup.py
- Specify `--artifactory-user-name` and `--artifactory-api-key` as optional for the following commands:
- `dg cluster install-assembly`
- `dg cluster install-cloud-pak-for-data`
- `dg cluster install-data-gate`
- `dg cluster install-db2`
=> Specify --artifactory-user-name and --artifactory-api-key as optional

dg/lib/cloud_pak_for_data/cpd_3_5_0/cpd_manager.py
- Add support for installing the [January 2021 refresh of Cloud Pak for Data 3.5.0](https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_latest/cpd/overview/whats-new.html#whats-new__dec2020#whats-new__dec2020) using [Cloud Pak for Data 3.5.2 Installer](https://github.com/IBM/cpd-cli/releases/tag/v3.5.2).
- This change was tested using a FYRE cluster.
=> Add support for cpd-cli 3.5.2

dg/commands/ibmcloud/cluster/create.py
This pull request fixes the following error during cluster creation:
```
The specified flavor is deprecated. (E0146)
To list available flavors for a location, run 'ibmcloud ks flavors --zone <zone>'.
```
I looks like flavor `b2c.16x64` was replaced with flavor `b3c.16x64`.
=> Fix IBM Cloud error during cluster creation

dg/commands/fyre/cluster/init_node_for_db2.py, dg/commands/fyre/cluster/install_nfs_storage_class.py, dg/lib/fyre/network.py, dg/lib/fyre/nfs.py, dg/lib/fyre/openshift.py, dg/lib/openshift.py, dg/utils/network.py, dg/utils/ssh.py, setup.py, test/lib/fyre/test_network.py, test/utils/test_network.py
- Added support for executing `dg fyre cluster install-nfs-storage-class` on infrastructure node
- Move logic from `dg/commands/fyre/cluster/install_nfs_storage_class.py` to `dg/lib/fyre/network.py`
- Added support for executing `dg fyre cluster init-node-for-db2` on infrastructure node
- Move logic from `dg/commands/fyre/cluster/init_node_for_db2.py` to `dg/lib/fyre/openshift.py`
- Add unit tests
=> Support executing FYRE-related commands on infrastructure node

.vscode/settings.json, README.md, dg/commands/adm/__init__.py, dg/commands/adm/config/__init__.py, dg/commands/cluster/__init__.py, dg/commands/fyre/__init__.py, dg/commands/fyre/cluster/__init__.py, dg/commands/ibmcloud/__init__.py, dg/commands/ibmcloud/cluster/__init__.py, dg/commands/ibmcloud/nuclear/__init__.py
- Add support for automatically sorting imports on save in Visual Studio Code
- Sort imports of several `__init__.py` files
=> Add support for automatically sorting imports on save

dg/lib/click/lazy_loading_multi_command.py
- `LazyLoadingMultiCommand::get_command()` now returns `None` instead of raising an error to fix shell completion in case of an unknown command.
=> Fix shell completion in case of unknown command

dg/deps/autocomplete/dg-autocomplete-bash.sh, dg/deps/autocomplete/dg-autocomplete-zsh.sh, setup.py
- Use Click 8 as the `click-option-group` package now supports it
- Update shell completion scripts (generated by Click 8)
=> Use Click 8

dg/commands/ibmcloud/oc/cluster/create.py, dg/config/data_gate_configuration_manager.py, dg/lib/fyre/api_manager.py, dg/lib/fyre/cluster/ocpplus_cluster.py, dg/lib/fyre/data/ocpplus_cluster_specification.py, dg/lib/ibmcloud/ks/cluster/iks_cluster.py, tests/test/commands/cluster/test_cluster_commands.py, tests/test_fyre/test_fyre_commands.py
- Fix Pylance problems occurring due to a newer Pylance version
Additional information:
The following code seems to be redundant, but Pylance cannot determine that the first method already checks for `None` and therefore creates a warning in Visual Studio Code:
```
self.assertIsNotNone(cluster)
if cluster is None:
raise TypeError()
```
This issue can be solved with Python 3.10, which will introduce [user-defined type guards](https://www.python.org/dev/peps/pep-0647/).
=> Fix Pylance problems

dg/commands/fyre/cluster/transfer_ownership.py, dg/lib/fyre/api_manager.py, dg/lib/fyre/types/ocp_transfer_put_request.py
- Add support for transferring ownership of a FYRE cluster to another product group (see [Slack announcement](https://ibm-analytics.slack.com/archives/C0ZF8PWBY/p1625779179092200))
=> Add support for transferring ownership of a FYRE cluster to another product group

.vscode/settings.json, dg/lib/error.py, dg/lib/fyre/data/ocp_available_data.py, dg/lib/fyre/data/product_group_quota_data.py, dg/lib/fyre/data/quick_burn_size_data.py, dg/lib/fyre/response_managers/ocp_available_get_response_manager.py, dg/lib/fyre/response_managers/ocp_quick_burn_sizes_response_manager.py, dg/lib/fyre/response_managers/quota_get_response_manager.py, dg/lib/fyre/types/ocp_add_additional_nodes_put_request.py, dg/lib/fyre/types/ocp_available_get_response.py, dg/lib/fyre/types/ocp_post_request.py, dg/lib/fyre/types/ocp_quick_burn_sizes_response.py, dg/lib/fyre/types/ocp_resource_put_request.py, dg/lib/fyre/types/ocp_transfer_put_request.py, dg/lib/fyre/types/quota_get_response.py, tests/test_fyre/test_fyre_commands.py
- Fix `dg fyre info get-default-sizes` due to a change in one of the FYRE OCP+ APIs
- Fix `dg fyre info get-quick-burn-sizes` due to a change in one of the FYRE OCP+ APIs
- Fix `dg fyre info get-quota` due to a change in one of the FYRE OCP+ APIs
=> Fix 'dg fyre info get-quota'

dg/lib/error.py, dg/lib/ibmcloud/__init__.py, dg/lib/ibmcloud/status.py, dg/utils/process.py
- Store error output and standard output in `DataGateCLIException` class
- Raise `IBMCloudException` instead of `DataGateCLIException` when encountering an error in `execute_ibmcloud_command()`
- Ignore service unavailable errors (HTTP status code 503) when requesting IBM Cloud cluster status (these errors recently started to occur sporadically)
=> Ignore service unavailable errors when requesting IBM Cloud cluster status

dg/commands/ibmcloud/oc/cluster/create.py, dg/lib/ibmcloud/status.py, tests/test/commands/ibmcloud/dependencies/ibmcloud_oc_cluster_status_2.json
- Wait for Ingress components status using a separate command (see comment in `dg/commands/ibmcloud/oc/cluster/create.py`)
=> Fix 'dg ibmcloud oc cluster create'

dg/commands/fyre/cluster/create_for_db2_data_gate.py
- Use OpenShift 4.7 during Db2 Data Gate cluster creation as OpenShift 4.8 (default version) is not supported by Cloud Pak for Data 4.0.0
=> Use OpenShift 4.7 during Db2 Data Gate cluster creation

dg/lib/cloud_pak_for_data/cpd_4_0_0/cpd_manager.py
The custom resource delete event callback was failing because it was looking in a non-existent field in event.
This PR fixes this.
=> fix custom resource delete event callback

dg/lib/dependency_manager/__init__.py, dg/lib/dependency_manager/plugins/ibm_cloud_pak_cli_plugin.py
- Add IBM Cloud Pak CLI dependency manager plug-in (adds support for automatically downloading the IBM Cloud Pak CLI)
=> Add IBM Cloud Pak CLI dependency manager plug-in

cpo/commands/cpd4/service/install.py, cpo/deps/config/cpd-custom-resources.json, cpo/deps/config/cpd-operand-requests.json, cpo/deps/config/cpd-subscriptions.json, cpo/lib/cloud_pak_for_data/cpd_4_0_0/catalog_source_manager.py, cpo/lib/cloud_pak_for_data/cpd_4_0_0/cpd_manager.py, cpo/lib/cloud_pak_for_data/cpd_4_0_0/cpd_operand_manager.py, cpo/lib/cloud_pak_for_data/cpd_4_0_0/cpd_service_manager.py, cpo/lib/cloud_pak_for_data/cpd_4_0_0/types/custom_resource_event_data.py, cpo/lib/cloud_pak_for_data/cpd_4_0_0/types/operand_request_metadata.py, cpo/lib/cloud_pak_for_data/cpd_4_0_0/types/status_key_data.py, cpo/lib/cloud_pak_for_data/cpd_4_0_0/types/status_key_value.py, cpo/lib/cloud_pak_for_data/cpd_4_0_0/types/subscription_metadata.py, cpo/lib/openshift/openshift_api_manager.py, cpo/lib/openshift/types/custom_resource_event_result.py, cpo/utils/importlib.py, docs/installing_ibm_cloud_pak_for_data_on_a_fyre-based_openshift_cluster.md
- Add support for Cloud Pak for Data 4.0.4
- Add support for creating operand requests, which are a prerequisite for installing certain Cloud Pak for Data services
- Support "EDB Postgres" service installation
- Add default value to `--catalog-source` option of `cpo cpd4 service install command`
- Remove unused `ibm-db2uoperator-catalog` catalog source
=> Add Cloud Pak for Data 4.0.4 support

cpo/lib/fyre/response_managers/ocp_get_response_manager.py, cpo/lib/fyre/response_managers/ocp_get_response_manager_for_single_cluster.py
initial_ocp_version is not a required field because Fyre does not return it in case of a new cluster apparently.
=> https://github.com/IBM/cloud-pak-operations-cli/issues/111

cpo/lib/fyre/response_managers/ocp_get_response_manager_for_single_cluster.py, cpo/lib/fyre/types/ocp_get_response_for_single_cluster.py
- Re-add `kubeadmin_password` to OCP+ API response schema but make it optional (sometimes this key and the corresponding value are returned, sometimes not)
The Jenkins build pipeline is finally [green](https://idaa-jenkins.swg-devops.com/job/data-gate/job/data-gate-cli/job/fix_jenkins_pipeline/1/) again.
=> Fix Jenkins pipeline

cpo/commands/adm/ibm_internal_plugin/install.py, cpo/commands/adm/ibm_internal_plugin/list.py, cpo/lib/ibm_internal_plugin/install.py, cpo/lib/ibm_internal_plugin/list.py
This PR allows to authenticate by asking for flags instead of showing a prompt. This feature is necessary to use the plugin in our teams pipeline.
=> feat: Authenticate by asking for flags instead of showing a prompt

cpo/commands/cluster/use.py, cpo/config/cluster_credentials_manager.py
This pull request adds a `--login` option to the `cluster use` command, which allows logging in to the OpenShift cluster with the given alias or server URL.
=> Add --login option to 'cluster use' command
